local tODWhJwVu3j=tostring(27)
local i32tGa8fMkk23kyO=type(nil)
local wQVEJdQYfttvAYtyI=bit32.bxor(128,11)
local a42Ol47TvxHE0jQ=string.len("yIoTX5H3")
local kE1sb9qjPaU=tostring(20)
local oqn_ch1DxG7VkWy3XK=math.floor(1)
local hhNyMNVSKtiJYpfrWl=math.floor(4)
local fb7vLmNrIuNn3z=364
local ukRVx45xR=string.len("chZi")
local a_Fl8bjbG2=#"x7r_b"
local cKU5MJ2NPH5Z1vXhj=83
local l2fSkphUiurJxOjA=#"wkBEqm"
do local _=nil end
if false then error("") end
local b82sGwHw8BjtTEMAhv=type(nil)
local rS5kMd78y64IM=string.len("rPp9Nu6i")
for _=1,0 do end
if false then error("") end
for _=1,0 do end
local t80AfIF0KoGGaRSo={"a3277a5d83a5d4e13ba7f52bf588813021a91cc651a1dc2305bf5a5729375604ab9b3435f1b2bf7aff88ca985f74a","44d27fa8aa4c1e25d9da8821fef154e5b9a6a"}
local qanb3megSdIe={1,2}
local lk_9Vj5MpN={"e563a1b60dcc6c2670ba8d230465d4ab095","bf9087709ddb8c0d68d650d59ede8e5e16dd6aca099d61f9fca620bc348e92248465794ce2504a8b283473ee5e01c"}
local tSwczFEeqDXmm={2,1}
local q3JMurzshVAdF8B4I=math.abs(-1)
local xiQxMGRoTf34=439
local uidfMRAfvnt5O=math.floor(8)
do local _=nil end
if false then error("") end
do local _=nil end
local tQNTC10qYKC9OGWcYf={}
for uBwBSwXlH=1,#qanb3megSdIe do tQNTC10qYKC9OGWcYf[qanb3megSdIe[uBwBSwXlH]]=t80AfIF0KoGGaRSo[uBwBSwXlH] end
tQNTC10qYKC9OGWcYf=table.concat(tQNTC10qYKC9OGWcYf)
local u1DeGBy6vb={}
for uBwBSwXlH=1,#tSwczFEeqDXmm do u1DeGBy6vb[tSwczFEeqDXmm[uBwBSwXlH]]=lk_9Vj5MpN[uBwBSwXlH] end
u1DeGBy6vb=table.concat(u1DeGBy6vb)
local pA9FYZqngc={}
for uBwBSwXlH=1,#tQNTC10qYKC9OGWcYf,2 do
  pA9FYZqngc[#pA9FYZqngc+1]=tonumber(string.sub(tQNTC10qYKC9OGWcYf,uBwBSwXlH,uBwBSwXlH+1),16)
end
local qgqSUZNsac2C4h8RX={218,246,63,237,251,149,247,223,147,143,114,101,150,98,202,73,250,193,233,58,223,214,118,131,173,160,41,169,198,86,58,182,137,88,98,244,18,245,221,101,216}
for uBwBSwXlH=1,#pA9FYZqngc do
  pA9FYZqngc[uBwBSwXlH]=bit32.bxor(pA9FYZqngc[uBwBSwXlH],qgqSUZNsac2C4h8RX[(uBwBSwXlH-1)%#qgqSUZNsac2C4h8RX+1])
end
local aHVomSG4nrBSUhvgLU={}
for uBwBSwXlH=1,#u1DeGBy6vb,2 do
  aHVomSG4nrBSUhvgLU[#aHVomSG4nrBSUhvgLU+1]=tonumber(string.sub(u1DeGBy6vb,uBwBSwXlH,uBwBSwXlH+1),16)
end
local iTOw4err2H5cW={82,79,252,127,223,167,195,26,118,172,6,102,121,18,178,44,217,184,111,75,180,97,181,249,104,148,44,244,220,222,161,244,53,77,211,175,238,171,14,192,51}
for uBwBSwXlH=1,#aHVomSG4nrBSUhvgLU do
  aHVomSG4nrBSUhvgLU[uBwBSwXlH]=bit32.bxor(aHVomSG4nrBSUhvgLU[uBwBSwXlH],iTOw4err2H5cW[(uBwBSwXlH-1)%#iTOw4err2H5cW+1])
end
local twn0xUlysY_xITp_EE={}
for uBwBSwXlH=1,math.max(#pA9FYZqngc,#aHVomSG4nrBSUhvgLU) do
  if pA9FYZqngc[uBwBSwXlH] then twn0xUlysY_xITp_EE[#twn0xUlysY_xITp_EE+1]=pA9FYZqngc[uBwBSwXlH] end
  if aHVomSG4nrBSUhvgLU[uBwBSwXlH] then twn0xUlysY_xITp_EE[#twn0xUlysY_xITp_EE+1]=aHVomSG4nrBSUhvgLU[uBwBSwXlH] end
end
local wHt45FWzpjyprmZ743={}
local rGOuHbbhf9j=170353382
for uBwBSwXlH=#twn0xUlysY_xITp_EE-1,1,-1 do
  rGOuHbbhf9j=(rGOuHbbhf9j*1664525+1013904223)%4294967296
  local i02JwlI9AHHBoCC8H=rGOuHbbhf9j%(uBwBSwXlH+1)+1
  wHt45FWzpjyprmZ743[#wHt45FWzpjyprmZ743+1]={uBwBSwXlH+1,i02JwlI9AHHBoCC8H}
end
for uBwBSwXlH=#wHt45FWzpjyprmZ743,1,-1 do
  local udWtaAhsFkx=wHt45FWzpjyprmZ743[uBwBSwXlH]
  local mYqMCAaYs=twn0xUlysY_xITp_EE[udWtaAhsFkx[1]]
  twn0xUlysY_xITp_EE[udWtaAhsFkx[1]]=twn0xUlysY_xITp_EE[udWtaAhsFkx[2]]
  twn0xUlysY_xITp_EE[udWtaAhsFkx[2]]=mYqMCAaYs
end
local jKz3C6y19eqyy={}
local sAYLg_K5D1jr3L=584096551
for uBwBSwXlH=#twn0xUlysY_xITp_EE-1,1,-1 do
  sAYLg_K5D1jr3L=(sAYLg_K5D1jr3L*1664525+1013904223)%4294967296
  local dW3YeNKph=sAYLg_K5D1jr3L%(uBwBSwXlH+1)+1
  jKz3C6y19eqyy[#jKz3C6y19eqyy+1]={uBwBSwXlH+1,dW3YeNKph}
end
for uBwBSwXlH=#jKz3C6y19eqyy,1,-1 do
  local xmy3Wvs3DGJC8tSVN=jKz3C6y19eqyy[uBwBSwXlH]
  local o1kTHgdbiFrre81=twn0xUlysY_xITp_EE[xmy3Wvs3DGJC8tSVN[1]]
  twn0xUlysY_xITp_EE[xmy3Wvs3DGJC8tSVN[1]]=twn0xUlysY_xITp_EE[xmy3Wvs3DGJC8tSVN[2]]
  twn0xUlysY_xITp_EE[xmy3Wvs3DGJC8tSVN[2]]=o1kTHgdbiFrre81
end
local dhC9zC6eH8xnAVLNUt={117,232,18,29,2,30,78,210,88,154,160,83,236,70,167,139,82,197,148,43,16,111,44,33,7,120,28,142,223,156,112,247,57,160,32,43,55,75,237,103,245}
for uBwBSwXlH=1,#twn0xUlysY_xITp_EE do
  twn0xUlysY_xITp_EE[uBwBSwXlH]=bit32.bxor(twn0xUlysY_xITp_EE[uBwBSwXlH],dhC9zC6eH8xnAVLNUt[(uBwBSwXlH-1)%#dhC9zC6eH8xnAVLNUt+1])
end
local i0WP6fmI9Y3={73,20,18,43,247,33,185,50,231,118,127,96,75,39,98,23,43,23,60,162,39,169,132,250,90,41,55,37,202,121,161}
for uBwBSwXlH=1,#twn0xUlysY_xITp_EE do
  twn0xUlysY_xITp_EE[uBwBSwXlH]=bit32.bxor(twn0xUlysY_xITp_EE[uBwBSwXlH],i0WP6fmI9Y3[(uBwBSwXlH-1)%#i0WP6fmI9Y3+1])
end
local yEbNZ2MlFG0=math.abs(-5)
local adhTtP5EPAgX=bit32.bxor(158,91)
local iw7oWxJk2t8eMiIk=#"aWKn"
local i0HkmKDUI56Q=string.len("afJvsxd")
local y20X7fQSo=tostring(77)
local jYvBOBQVpA=type(nil)
for _=1,0 do end
for _=1,0 do end
for _=1,0 do end
local lhSFGhLy_0={174,41,224,32,184,71,73,252,241,30,143,231,102,157,128,185,116,237,63,203,203,3,72,208,206,24,110,109,77,185,187,100,50,114,146,112,115,116,159,151,7}
local w4_PjGgN1D9Wpp={}
for uBwBSwXlH=1,#twn0xUlysY_xITp_EE do
  w4_PjGgN1D9Wpp[uBwBSwXlH]=string.char(bit32.bxor(twn0xUlysY_xITp_EE[uBwBSwXlH],lhSFGhLy_0[(uBwBSwXlH-1)%#lhSFGhLy_0+1]))
end
local m3X33a7sUW8GMH6=table.concat(w4_PjGgN1D9Wpp)
local nGmfmNmCiQo9zC1x=string.len("besoNHLU")
local jCpgsZQKD7H99LBCTz=#"j7_WTG"
local s2_lvXW2LCZ4396h=math.floor(1)
local dR8TPau3MqXuAEMwOU=#"oyD"
if false then error("") end
do local _=nil end
local mWn93W1lbOxZ,cXIH7FqmrB5Fi=loadstring(m3X33a7sUW8GMH6)
if mWn93W1lbOxZ then
  mWn93W1lbOxZ()
else
  error("Mnx | Public Enemy : "..tostring(cXIH7FqmrB5Fi))
end
